# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 06:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_secrethashcode_expired_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secrethashcode',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 8, 13, 33, 14, 222804)),
        ),
    ]
