# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 12:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20161108_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secrethashcode',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 10, 19, 45, 9, 943694)),
        ),
    ]
