# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='administrator',
            new_name='soundman',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='administrator',
            new_name='soundman',
        ),
    ]
