# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20161110_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='current_duration',
            new_name='money_back',
        ),
        migrations.RemoveField(
            model_name='record',
            name='difference',
        ),
    ]
