# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20161027_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_record', models.DateTimeField(null=True)),
                ('stop_record', models.DateTimeField(null=True)),
                ('current_duration', models.DurationField(null=True)),
                ('difference', models.DurationField(null=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='bookings.Reservation')),
            ],
        ),
    ]
